# Generated by Django 5.2 on 2025-05-10 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EarningDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('date', models.DateField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tip', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('earning', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='earnings.earning')),
            ],
        ),
        migrations.CreateModel(
            name='Weeklypayments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('start', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ispaid_part1', models.CharField(choices=[('Yes', 'Yes'), ('Next', 'Next'), ('No', 'No')], max_length=4)),
                ('end', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ispaid_part2', models.CharField(choices=[('Yes', 'Yes'), ('Next', 'Next'), ('No', 'No')], max_length=4)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
