# Generated by Django 5.2 on 2025-05-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypayments',
            name='netpay1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklypayments',
            name='netpay2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
