# Generated by Django 5.2 on 2025-05-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0002_weeklypayments_netpay1_weeklypayments_netpay2'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypayments',
            name='nettotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
