# Generated by Django 5.2 on 2025-05-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0002_earning_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
