# Generated by Django 5.2 on 2025-05-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0003_weeklypayments_nettotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='earning',
            name='total_tip',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
