# Generated by Django 5.2 on 2025-05-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0003_earning_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='earning',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
