# Generated by Django 5.2 on 2025-05-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0004_earning_total_amount_earning_total_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypayments',
            name='total_amount1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklypayments',
            name='total_amount2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklypayments',
            name='total_tips1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklypayments',
            name='total_tips2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
