# Generated by Django 5.2 on 2025-05-23 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0005_weeklypayments_total_amount1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypayments',
            name='per30_1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='weeklypayments',
            name='per30_2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
