# Generated by Django 5.2 on 2025-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0007_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='percent30',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoices',
            name='percent4',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
