# Generated by Django 5.2 on 2025-05-25 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('earnings', '0008_invoices_percent30_invoices_percent4'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoices',
            name='revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
