# Generated by Django 5.2 on 2025-05-06 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GigWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_details', models.TextField()),
                ('duration_min', models.FloatField(default=0.0)),
                ('duration', models.DurationField()),
                ('distance_km', models.FloatField(default=0.0)),
                ('earning', models.FloatField(blank=True, null=True)),
                ('fuel_pay', models.FloatField(blank=True, null=True)),
                ('total_pay', models.FloatField(blank=True, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
