# Generated by Django 5.2 on 2025-05-06 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigwork',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
