# Generated by Django 5.2 on 2025-05-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigwork', '0003_alter_gigwork_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigwork',
            name='duration',
            field=models.FloatField(default=0.0),
        ),
    ]
