# Generated by Django 5.2 on 2025-05-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigwork', '0005_weeklyearning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyearning',
            name='ispaid_part1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.AlterField(
            model_name='weeklyearning',
            name='ispaid_part2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
    ]
