# Generated by Django 5.2 on 2025-05-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigwork', '0006_alter_weeklyearning_ispaid_part1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyearning',
            name='ispaid_part1',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Next', 'Next'), ('No', 'No')], max_length=4),
        ),
        migrations.AlterField(
            model_name='weeklyearning',
            name='ispaid_part2',
            field=models.CharField(choices=[('Yes', 'Yes'), ('Next', 'Next'), ('No', 'No')], max_length=4),
        ),
    ]
