# Generated by Django 5.2 on 2025-05-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigwork', '0008_weeklyearning_netpay1_weeklyearning_netpay2'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyearning',
            name='nettotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
