# Generated by Django 5.2 on 2025-05-31 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigwork', '0010_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='percent30',
        ),
    ]
