# Generated by Django 5.2 on 2025-05-31 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigwork', '0011_remove_payments_percent30'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
