# Generated by Django 5.2 on 2025-05-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gigwork', '0012_payments_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payments',
            name='amounts',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='tips',
        ),
    ]
