# Generated by Django 5.2 on 2025-05-31 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gigwork', '0013_remove_payments_amounts_remove_payments_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='health_ins',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
